name: NDNServerPlugin
main: com.ndn.bukkitplugin.ndnserverplugin.NDNServerPlugin
version: 0.2
api-version: 1.13
author: NDN Dev Group
commands:
   account:
      description: Root command for the accounts system.
      usage: /<command> [subcommand(help, send, bal)] [player] [amount] [message]
   pay:
      description: Simple command to pay other players. Same as /account send
      usage: /<command> [player] [amount]
   clearweather:
      description: Clear the skies with the power of money. Makes rain dissapear for $10
      usage: /<command>
   spawn:
      description: Teleport to spawn for a high cost
      usage: /<command>
   firework:
      description: Create a random firework! (OPs only)
      usage: /<command>
   town:
      description: Root command for town commands. Use /town help for more information.
      usage: /<command> [parameters]
   dbinfo:
      description: Displays db connection info. Must be oped to use! Only for development purposes!
      usage: /<command>
   signshop:
      description: Displays sign shop help
   executeexpenses:
      description: Executes daily expenses code that usually runs at midnight. Must be oped to use! Only for development purposes!
      usage: /<command>
   quest:
      description: Home of all the quest commands!
      usage: /<command>
   zombiepatrol:
      description: Testing command. Do not use!
      usage: /<commad>